services:
  django:
    container_name: django_app
    build:
      context: .
      dockerfile: ./Dockerfile
    command: python djangotutorial/manage.py runserver 0.0.0.0:8000
    ports:
      - 8000:8000
    volumes:
      - .:/app:cached
      - vscode-extensions:/root/.vscode-server/extensions
    depends_on:
      - postgres
  postgres:
    container_name: postgres
    image: postgres:14.19-alpine
    user: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-pgpassword}
      - POSTGRES_DB=${POSTGRES_DB:-django}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped
  redis:
    image: redis:7.0.15
    container_name: redis
    environment:
      - REDIS_DATABASES=1
    ports:
      - 6379:6379
    volumes:
      - redis-data:/data
  redisinsight:
    image: redislabs/redisinsight:latest
    container_name: redisinsight
    ports:
      - 5540:5540
    volumes:
      - redisinsight-data:/data

volumes:
  vscode-extensions:
  postgres-data:
  redis-data:
  redisinsight-data:
