services:
  django:
    build:
      context: .
      dockerfile: ./Dockerfile
    command: python djangotutorial/manage.py runserver 0.0.0.0:8000
    ports:
      - 8000:8000
    volumes:
      - .:/app:cached
    environment:
      PYTHONWARNINGS: default
      PYTHONBREAKPOINT: ipdb.set_trace
    depends_on:
      - postgres
  postgres:
    image: postgres:14.19-alpine
    user: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-pgpassword}
      - POSTGRES_DB=${POSTGRES_DB:-django}
    volumes:
      # with named volume we will persist database state E.g after restarting docker/machine
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped
  redis:
    image: redis:7.0.15
    container_name: redis_container
    environment:
      - REDIS_DATABASES=1
    ports:
      - 6379:6379
    volumes:
      - redisdata:/data



volumes:
  postgres-data:
  redisdata:
